site_name: My Docs
theme:
  name: material
  # Ref: https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  custom_dir: overrides
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons
  icon:
    logo: material/file-document-outline
  favicon: assets/images/favicon.png
  features:
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.indexes
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    - toc.follow
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing
    - search.share
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#mark-as-read
    - announce.dismiss
    # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/
    - navigation.footer

plugins:
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
  - search
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards
  - social
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags:
      tags_file: tags.md

extra:
  # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX # Google Analytics 4
  # TODO (Set up site analytics):
  # - Uncomment the `analytics` section above
  # - Refer to the link below for remaining steps:
  #       https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics

  # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # social:
  #   - icon: fontawesome/brands/github
  #     link: <link>
  # TODO (Add social links):
  # - Uncomment the `social` section above
  # - Refer to the link below for remaining steps:
  #       https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links

# Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
# copyright: Copyright &copy; 2023 <name>
# TODO (Set up copyright notice):
# - Uncomment the `copyright` line above and enter your name

# Ref: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/j3soon/mkdocs-material-template
# repo_name: j3soon/mkdocs-material-template
# TODO (Set up git repository):
# - Replace the `repo_url`/`repo_name` above to your repository URL
